### ISSUE TITLE
Local testing of ATOM image via Rigel

### ISSUE THREAD

**Issue by Kazadhum** [Kazadhum/atom#3]
The third goal here is to get Rigel to automatically test the generated docker image locally, using:

>`rigel run job test`

Or, if the "test" sequence only has the test job:

>`rigel run sequence test`

**Comment by Kazadhum** [comment]
Hi @rarrais, @MisterOwlPT and @sergiodmlteixeira! I was wondering how to make it so the introspection part of the test plugin only require a timeout as we discussed in our meeting

**Comment by rarrais** [comment]
Hi,

@MisterOwlPT can you @Kazadhum help with an example of one of our Rigelfiles where we had the need to do this?

Thank you!

**Comment by MisterOwlPT** [comment]
Hi,

The _local test_ plugin terminates whenever one of the following events happens:
- All functional requirements were satisfied;
- **The timeout limit was reached _before_ all requirements were satisfied**; 

At the moment the _local test_ plugin **must always be passed some functional requirements**. Otherwise, it will terminate immediately. My recommendation is therefore for @Kazadhum  to specify a requirement that will _never_ be satisfied while setting the _timeout_ value for the desired duration of execution. Since the requirement will never be satisfied, the plugin will "wait" until the timeout happens, only then finishing its execution.

You can use this Rigelfile excerpt **as an example** (adapt/fill the missing parts for your use case):
```YAML
test:
  plugin: "rigel.plugins.core.TestPlugin"
  with:
    timeout: 60.0 # seconds (1.0m * 60.0s)
    components:
      -
        name: "<NAME>"
        image: "<IMAGE_NAME>:latest"
        command: ["roslaunch", "<PKG>", "<LAUNCHFILE>"]
        introspection:
          requirements:
            - 'globally: some /dummy_topic [std_msgs/String]'
```

In this example,  the plugin will wait for a ROS message of type `std_msgs/String` to be published on ROS topic `/dummy_topic`. **It's okay if the ROS topic is not used at all by any node**. Just make sure that it stays like that 😉 

You can alter the _timeout_ field according to your need. At the moment it is said to finish execution after _1 minute_ (60.0 _seconds_). Change this value as per your need (just make sure to work in _seconds_). By default, the plugin uses _10 minutes_ (600.0 seconds).

**WARNING**: *I had to make some changes to the [Rigel](https://github.com/rigel-ros/rigel/tree/develop) source-code*. I kindly ask @Kazadhum  to `git pull` these new changes and to `poetry install` Rigel again for you to be able to use the YAML above. Sorry for this inconvenience.

Please let me know if you have any trouble or doubt 😃
